language: node_js
node_js:
  - "0.12"
script:
  - npm install -g mocha istanbul coveralls
  - APP_ENV=test istanbul cover _mocha -- -R spec tests/
  - node tests/integration/watchtowerTest.js
  - coveralls < coverage/lcov.info
