sites:
  - name: "BBC"
    base: "http://bbc.co.uk"
    endpoints:
      - name: "News Home Page"
        path: "/news"
      - name: "Election 2015 Home Page"
        path: "/news/election/2015"
  - name: "Guardian"
    base: "http://theguardian.com"
    endpoints:
      - name: "UK Home Page"
        path: "/uk"
      - name: "Sport Home Page"
        path: "/uk/sport"
